### ISSUE TITLE
Uncaught Error: kill EPERM

### ISSUE THREAD

**Issue by SNWK** [abe33/atom-pigments#413] opened 2018-10-19 13:25 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Unknown Windows version
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package 0.40.2

### Stack Trace

Uncaught Error: kill EPERM

```
At events.js:183

Error: kill EPERM
    at _errnoException (util.js:1024:11)
    at ChildProcess.kill (internal/child_process.js:395:26)
    at Task.module.exports.Task.terminate (~/AppData/Local/atom/app-1.31.2/resources/app/src/task.js:148:31)
    at ColorBuffer.module.exports.ColorBuffer.terminateRunningTask (/packages/pigments/lib/color-buffer.coffee:166:35)
    at /packages/pigments/lib/color-buffer.coffee:33:8
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at disposables.add.displayLayer.onDidChange.changes (~/AppData/Local/atom/app-1.31.2/resources/app/src/text-editor.js:615:26)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at DisplayLayer.emitDeferredChangeEvents (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/text-buffer/lib/display-layer.js:819:26)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/text-buffer/lib/text-buffer.js:1802:30)
    at TextBuffer.module.exports.TextBuffer.transact (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/text-buffer/lib/text-buffer.js:998:18)
    at TextEditor.transact (~/AppData/Local/atom/app-1.31.2/resources/app/src/text-editor.js:2007:30)
    at TextEditor.moveCursors (~/AppData/Local/atom/app-1.31.2/resources/app/src/text-editor.js:2880:23)
    at TextEditor.setCursorScreenPosition (~/AppData/Local/atom/app-1.31.2/resources/app/src/text-editor.js:2691:23)
    at TextEditorComponent.didMouseDownOnContent (~/AppData/Local/atom/app-1.31.2/resources/app/src/text-editor-component.js:1808:25)
```

### Commands

```
     -2:22 snippets:next-tab-stop (input.hidden-input)
     -2:22 snippets:expand (input.hidden-input)
     -2:22 editor:indent (input.hidden-input)
     -2:20.2.0 markdown:strong-emphasis (input.hidden-input)
     -2:17.9.0 core:move-down (input.hidden-input)
     -2:17.4.0 core:move-left (input.hidden-input)
     -2:16.8.0 editor:newline (input.hidden-input)
  5x -2:13.7.0 core:backspace (input.hidden-input)
  2x -1:46.5.0 core:paste (input.hidden-input)
     -1:27.6.0 editor:newline (input.hidden-input)
     -0:59.5.0 core:backspace (input.hidden-input)
     -0:58.3.0 editor:newline (input.hidden-input)
  3x -0:57.8.0 core:backspace (input.hidden-input)
     -0:55.7.0 markdown:strong-emphasis (input.hidden-input)
     -0:32.3.0 markdown-img-paste:paste (input.hidden-input)
     -0:28.9.0 core:move-right (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.1 
atom-clock 0.1.16 
busy-signal 1.4.3 
file-icons 2.1.24 
gcc-make-run 0.2.12 
git-plus 8.1.0 
intentions 1.1.5 
language-markdown 0.26.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
markdown-img-paste 0.3.11 
markdown-preview-plus 3.6.3 
markdown-scroll-sync 2.1.2 
markdown-themeable-pdf 1.2.1 
minimap 4.29.8 
pdf-view 0.71.0 
pigments 0.40.2 
pretty-json 2.0.3 
set-syntax 0.4.0 
simplified-chinese-menu 5.3.5 
```

**Comment by C-Bouthoorn** [comment] 2018-10-22 13:17
Duplicate of #411

**Closed by C-Bouthoorn** 2018-10-22 13:17 UTC
