### ISSUE TITLE
Pigments v0.40.2 freeze Atom – bootswatch repository

### ISSUE THREAD

**Issue by neumayr** [abe33/atom-pigments#371] opened 2017-12-12 20:26 UTC
#### Steps to reproduce

    $ cd ~/tmp
    $ git clone https://github.com/thomaspark/bootswatch.git
    $ cd bootswatch
    $ atom .

    open file `dist/cerulean/_variables.scss`
    open file `dist/cerulean/_bootswatch.scss`
    Wait 3-5 seconds 
    => Atom freeze

#### System

* Atom v1.25.1
* Pigments v0.40.2 
* Mac OS X 10.13.4 High Sierra

Tested on different machines.

**Comment by unti1x** [comment] 2017-12-18 12:20
Ubuntu 16.04.3
Pigments hangs whole system.

**Comment by pedrompr** [comment] 2018-04-17 20:34
It just happened to me.
Ubuntu 14.04
Atom 1.24.1
Once I installed pigments it consumed all available memory (up to 4GB RAM), forcing OS to use swap and freezing it all. Disabling it was enough for it not to happen again.

**Comment by C-Bouthoorn** [comment] 2018-09-19 12:14
Duplicate of https://github.com/abe33/atom-pigments/issues/351

**Closed by C-Bouthoorn** 2018-09-19 12:14 UTC
Labels: bug
