### ISSUE TITLE
when i install pigment in my atom editor- editor not responding 

### ISSUE THREAD

**Issue by Sujeetdihuli** [abe33/atom-pigments#397] opened 2018-05-10 07:11 UTC

**Comment by Kivylius** [comment] 2018-05-10 13:27
same here complete crash atom and even my pc (mac) on latest version of everything.

**Comment by GaetanQucit** [comment] 2018-05-18 09:31
Ran into the same problem !

**Comment by C-Bouthoorn** [comment] 2018-05-21 14:50
Duplicate of https://github.com/abe33/atom-pigments/issues/351

@GaetanQucit Try clearing your apm cache and installing again, it seems the files are corrupted

**Closed by C-Bouthoorn** 2018-05-21 14:50 UTC
