### ISSUE TITLE
BUG-Failed to activate the pigments package

### ISSUE THREAD

**Issue by songfeido** [abe33/atom-pigments#318] opened 2017-07-13 03:02 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package 0.39.1

### Stack Trace

Failed to activate the pigments package

```
At this.variableExpressionsRegistry.onDidUpdateExpressions is not a function

TypeError: this.variableExpressionsRegistry.onDidUpdateExpressions is not a function
    at /packages/pigments/lib/color-project.coffee:106:53)
    at Object.activate (/packages/pigments/lib/pigments.coffee:21:11)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:645:40)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.18.0/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:603:52)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:846:34
```

### Commands

```
  2x -3:29 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-dark-ui)
```

### Non-Core Packages

```
atom-ternjs 0.18.3 
autoclose-html 0.23.0 
autocomplete-paths 1.0.5 
autoprefixer 3.7.1 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.8 
highlight-selected 0.13.1 
intentions 1.1.2 
linter 2.2.0 
linter-ui-default 1.6.2 
minimap 4.28.3 
pigments 0.39.1 
tree-view-finder 0.2.1 
```

**Comment by songfeido** [comment] 2017-07-13 03:02
.

**Comment by balazsorban44** [comment] 2017-07-15 14:16
Same problem here, only on 1.19.0-beta3

**Comment by rbardini** [comment] 2017-07-17 12:32
Same here. Just installed `1.19.0-beta4` on top of an older version, but it didn't fix the issue.

**Comment by jt3k** [comment] 2017-07-17 13:31
same

**Comment by mikefuhan** [comment] 2017-07-17 17:42
same

**Comment by merlin-demay** [comment] 2017-07-17 17:44
Happened on Ubuntu 16.04 with 1.19.0-beta3 x64

```
Error: Cannot find 'highlights-component' in the require cache.
    at requireCore (~/.atom/packages/pigments/lib/pigments.coffee:310:19)
    at Object.patchAtom (~/.atom/packages/pigments/lib/pigments.coffee:312:26)
    at Object.activate (~/.atom/packages/pigments/lib/pigments.coffee:16:6)
    at Package.module.exports.Package.activateNow (/usr/share/atom-beta/resources/app/src/package.js:253:25)
    at /usr/share/atom-beta/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/usr/share/atom-beta/resources/app/src/package.js:99:21)
    at /usr/share/atom-beta/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/usr/share/atom-beta/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom-beta/resources/app/src/package-manager.js:645:40)
    at /usr/share/atom-beta/resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/usr/share/atom-beta/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/usr/share/atom-beta/resources/app/src/buffered-process.js:338:17)
    at /usr/share/atom-beta/resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (/usr/share/atom-beta/resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

**Comment by vagonzalez** [comment] 2017-07-18 10:56
Same

**Comment by scottosmith** [comment] 2017-07-19 14:52
Same

**Comment by jermashley** [comment] 2017-07-19 15:41
@abe33 Any idea when we might get a fix?

**Comment by Stanzilla** [comment] 2017-07-19 22:50
Same

**Comment by cbcoutinho** [comment] 2017-07-20 06:21
same

**Comment by rubenjimenez** [comment] 2017-07-20 13:37
same

**Comment by hkdeven** [comment] 2017-07-20 15:13
same

**Comment by felipe4253** [comment] 2017-07-20 16:32
same

**Comment by rthomas98** [comment] 2017-07-20 22:31
same

**Comment by rpmonteiro** [comment] 2017-07-21 08:15
same

**Comment by sdir01** [comment] 2017-07-21 12:24
Maybe somebody will fix it? No? Okay 😞

**Comment by m4r1vs** [comment] 2017-07-22 18:39
same here: 1.19.0-beta4 Windows 10

**Comment by mitsuzero** [comment] 2017-07-24 03:25
same version Manjaro Linux y 1.19.0-beta4 .

**Comment by lednhatkhanh** [comment] 2017-07-24 04:13
Same here, Fedora 26 64bit

**Comment by lednhatkhanh** [comment] 2017-07-24 04:14
Sooo, this issue has been reported for quite a long time but still no response, is this package abandoned?

**Comment by C-Bouthoorn** [comment] 2017-07-24 12:37
This is the same issue as https://github.com/abe33/atom-pigments/issues/314. The reason why this broke is stated there. Closing this issue

**Closed by C-Bouthoorn** 2017-07-24 12:37 UTC

**Comment by enoversum** [comment] 2017-07-27 08:35
Sorry to say, but I cannot reproduce this as being closed/fixed. As soon as I have pigments (re-)installed and enabled, it throws 'Cannot read property 'NaN' of undefined' as an error.

**Comment by C-Bouthoorn** [comment] 2017-08-07 20:01
@enoversum That error doesn't seem to be the same as this issue, could you please open a new issue (with a full stack trace of that error)?

**Comment by evwebcoder** [comment] 2017-08-08 17:42
Same, I update Atom to 1.19.0 and after restarting the Atom I got that issue.

**Comment by Ky6uk** [comment] 2017-08-08 18:06
@evwebcoder Did you upgrade the package to `v0.40.1`? It was fixed after the upgrading.

**Comment by cwonrails** [comment] 2017-08-08 18:21
@Ky6uk is correct - just updated my pigments package and all is well now.

**Comment by martezconner** [comment] 2017-08-08 18:30
updated the pigments package and it fixed my issue

**Comment by dertin** [comment] 2017-08-08 19:38
same

**Comment by cPress** [comment] 2017-08-08 20:32
Looks like version 0.40.1 on Atom 1.19.0 x64 works.

**Comment by realsrikar** [comment] 2017-08-08 21:12
same

**Comment by polyskalov** [comment] 2017-08-08 21:26
Click on the bug icon in the status bar, on the opened page click «rebuild packages»

**Comment by evwebcoder** [comment] 2017-08-09 01:02
@Ky6uk 
I just updated my pigments package and all working fine now. Thanks

**Comment by sajelgoel** [comment] 2017-10-06 16:14
Try this: https://youtu.be/dRhXjz7-Rro
