### ISSUE TITLE
MarkerType:dot  

### ISSUE THREAD

**Issue by wagnlinzh** [abe33/atom-pigments#187] opened 2016-05-22 11:57 UTC
MakerType:dot

![2](https://cloud.githubusercontent.com/assets/3985726/15453846/528d1dee-2057-11e6-857f-845c521fdebf.png)

![snipshot](https://cloud.githubusercontent.com/assets/3985726/15453838/209c3afe-2057-11e6-9eeb-851f7448e62e.png)

**Comment by GU5TAF** [comment] 2016-05-23 13:41
Duplicate of #178

**Comment by abe33** [comment] 2016-05-26 10:22
Yup, thanks @GU5TAF, closing in favor of the original.

**Closed by abe33** 2016-05-26 10:22 UTC
