### ISSUE TITLE
Pigments Lag Problem

### ISSUE THREAD

**Issue by zeNn-G** [abe33/atom-pigments#466] opened 2021-03-08 09:50 UTC
I'm having typing lag when i try to do something in Atom.I disabled all the packages and renabled again one by one and when i enable pigments its lagy again.Should i downgrade pigments.

My Atom Ver:1.54.0
My pigment Ver:0.40.6

**Comment by Cxarli** [comment] 2021-03-11 10:50
Duplicate of #351

**Closed by Cxarli** 2021-03-11 10:50 UTC
