### ISSUE TITLE
Makes editor lag.

### ISSUE THREAD

**Issue by kasiraket** [abe33/atom-pigments#296] opened 2017-04-12 19:42 UTC
When jumping between lines of code - Atom just freezes for a second or so.

**Comment by Memnarch1113** [comment] 2017-04-13 06:50
I have this same issue. Confirmed with Package Cop that Pigments is the troublemaker!

**Comment by SureWeb** [comment] 2017-04-15 15:37
Same here. I uninstalled Pigments and now there is no lag.

**Comment by garrettw** [comment] 2017-04-28 16:33
Same. I can't tell if it's the size of my CSS file (or the number of colors in it) making it lag... but I have noticed that high CPU usage is the culprit when it slows down.

**Comment by garrettw** [comment] 2017-04-28 16:40
possible duplicate of #275

**Comment by C-Bouthoorn** [comment] 2017-08-10 21:42
Indeed a duplicate of #275

**Closed by C-Bouthoorn** 2017-08-10 21:42 UTC
