### ISSUE TITLE
"@media (max/min-device-width/height)" highlight

### ISSUE THREAD

**Issue by JakeScervino** [abe33/atom-pigments#290] opened 2017-03-24 19:54 UTC
Whenever I use `@media (max/min-device-width/height)` it gets highlighted in a yellow colour and it's really annoying.
![screenshot 1](https://cloud.githubusercontent.com/assets/17952894/24311334/11b31280-10aa-11e7-86d2-b0700ea7465a.png)

**Comment by C-Bouthoorn** [comment] 2017-03-25 09:29
For reference: This colour is #e0c285

**Comment by abe33** [comment] 2017-03-27 14:25
I highly doubt it comes from Pigments, you're using dot decorations and pigments never mixes up decorations styles. It looks like some linter thing to me, but without being able to inspect the DOM it's hard to tell.

**Comment by JakeScervino** [comment] 2017-03-27 18:31
You are probably right, but I can't think of any other plugins that I have installed on atom that would be causing this problem. The only other packages I have installed are: emmet, atom-bootstrap4, and minimap. These other packages I have installed shouldn't be causing this problem, but maybe I'm wrong?

**Comment by C-Bouthoorn** [comment] 2017-03-31 14:21
Could you try disabling all other plugins and see if it's still there?

**Comment by JakeScervino** [comment] 2017-03-31 15:43
I already did that.... still no change. I have had pigments before and I've never had this problem until I recently factory reset my laptop and reinstalled atom, along with all of my old plugins. If no one else is having the same problem as me, it might just be my computer or atom may have not installed correctly for me. I'll still try to troubleshoot somethings and see if I can fix the issue I'm having, and if I figure it out I'll let you know.

**Comment by C-Bouthoorn** [comment] 2017-04-09 09:56
Does this happen in every project you make or only this specific project? I think pigments thinks something is a colour variable when it shouldn't.

**Comment by C-Bouthoorn** [comment] 2017-09-22 19:44
Seems to have been fixed. Closing

**Comment by jack-Greenberg** [comment] 2017-10-17 05:10
Was this ever resolved? I have the same issue and cannot find resolution anywhere online.

**Comment by C-Bouthoorn** [comment] 2017-10-17 15:13
Due to a lack of information, it was closed. If you can reproduce the issue for us, we will continue investigating where it comes from :blush:

**Comment by SkyHawkB** [comment] 2018-05-13 21:35
I am having this exact issue right now...

**Comment by SkyHawkB** [comment] 2018-05-13 21:37
Issue:
![image](https://user-images.githubusercontent.com/29524963/39971987-103ce310-56d4-11e8-9ea2-9e4aa1e6fe99.png)

Packages:
atom-chat, atom-clock, atom-html-preview, language-batchfile, teletype, tree-view-sort

**Comment by SkyHawkB** [comment] 2018-05-13 21:44
Element in question:
`<span class="syntax--invalid syntax--deprecated syntax--media syntax--css">device-width</span>`

**Comment by SkyHawkB** [comment] 2018-05-13 21:51
The reason for this issue is that it is marked as deprecated, and Atom is marking it as such.

**Comment by SkyHawkB** [comment] 2018-05-13 21:52
@C-Bouthoorn this issue is resolved, you can close this now.

**Comment by SkyHawkB** [comment] 2018-05-13 21:54
@C-Bouthoorn this issue is resolved, you can close this now.

**Comment by C-Bouthoorn** [comment] 2018-05-21 15:01
@SkyHawkB Thanks for your investigation! I'll close this PR :blush:

**Closed by C-Bouthoorn** 2018-05-21 15:01 UTC
Labels: bug, more-information-needed
