### ISSUE TITLE
Uncaught Error: kill EPERM

### ISSUE THREAD

**Issue by daisydam** [abe33/atom-pigments#392] opened 2018-04-10 02:15 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package 0.40.2

### Stack Trace

Uncaught Error: kill EPERM

```
At events.js:163

Error: kill EPERM
    at exports._errnoException (util.js:1050:11)
    at ChildProcess.kill (internal/child_process.js:400:26)
    at Task.module.exports.Task.terminate (~/AppData/Local/atom/app-1.25.1/resources/app/src/task.js:148:31)
    at ColorBuffer.module.exports.ColorBuffer.terminateRunningTask (/packages/pigments/lib/color-buffer.coffee:166:35)
    at /packages/pigments/lib/color-buffer.coffee:33:8
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at disposables.add.displayLayer.onDidChange.changes (~/AppData/Local/atom/app-1.25.1/resources/app/src/text-editor.js:595:26)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayLayer.emitDeferredChangeEvents (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/text-buffer/lib/display-layer.js:819:26)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:1756:30)
    at TextBuffer.module.exports.TextBuffer.transact (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:975:18)
    at TextEditor.transact (~/AppData/Local/atom/app-1.25.1/resources/app/src/text-editor.js:1839:30)
    at TextEditor.moveCursors (~/AppData/Local/atom/app-1.25.1/resources/app/src/text-editor.js:2708:23)
    at TextEditor.setCursorScreenPosition (~/AppData/Local/atom/app-1.25.1/resources/app/src/text-editor.js:2519:23)
    at TextEditorComponent.didMouseDownOnContent (~/AppData/Local/atom/app-1.25.1/resources/app/src/text-editor-component.js:1801:25)
```

### Commands

```
     -0:31.9.0 core:move-down (input.hidden-input)
     -0:31.7.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:31.7.0 editor:newline (input.hidden-input)
     -0:30.6.0 core:select-up (input.hidden-input)
     -0:30.4.0 editor:select-to-end-of-line (input.hidden-input)
     -0:30 core:backspace (input.hidden-input)
     -0:29.6.0 core:save (input.hidden-input)
     -0:22.6.0 core:move-down (input.hidden-input)
     -0:22.2.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:22 core:move-left (input.hidden-input)
     -0:17.4.0 core:save (input.hidden-input)
     -0:15.9.0 core:move-right (input.hidden-input)
     -0:15.5.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:15 core:select-up (input.hidden-input)
     -0:14.8.0 core:backspace (input.hidden-input)
     -0:14.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
autoclose-html 0.23.0 
code-peek 1.4.21 
emmet 2.4.3 
jackhammer-syntax 1.1.0 
join-lines-smarter 2.0.1 
jshint 1.8.6 
linter 2.0.0 
minimap 4.29.7 
pigments 0.40.2 
prettier-atom 0.49.2 
remote-ftp 2.1.4 
sass-autocompile 0.13.5 
script 3.17.3 
seti-syntax 1.1.3 
seti-ui 1.10.0 
```

**Comment by C-Bouthoorn** [comment] 2018-04-10 15:11
Duplicate of #373

**Closed by C-Bouthoorn** 2018-04-10 15:11 UTC
