### ISSUE TITLE
Atom is crashing when uninstall and install pigments package

### ISSUE THREAD

**Issue by HadasKharilker** [abe33/atom-pigments#473] opened 2021-08-10 10:41 UTC
Atom is crashing when uninstall and install pigments package(right away)
used the 1.58 atom version
and the 0.40.6 pigments package
reproduced all the time

**Comment by Cxarli** [comment] 2021-08-22 13:18
Duplicate of #351

**Closed by Cxarli** 2021-08-22 13:18 UTC
