### ISSUE TITLE
Causing the Atom 1.19 to crash

### ISSUE THREAD

**Issue by iawia002** [abe33/atom-pigments#330] opened 2017-08-10 01:55 UTC
after i upgrade to pigments 0.40.2, atom crashed every time i open it. But when i disable pigments, atom returns to normal.

Atom 1.19
macOS 10.12.3

**Comment by rlitman-10c** [comment] 2017-08-10 08:28
I can confirm that (Atom 1.19 on Windows). Atom forks a lot of processes related to pigments. Command lines are like:
...\atom.exe ...\atom\app-1.19.0\resources\app\src\task-bootstrap.js ...\.atom\compile-cache ...\.atom\packages\pigments\lib\tasks\scan-buffer-colors-handler.coffee

**Comment by sbritz** [comment] 2017-08-11 08:05
Yes, I agree (Atom 1.19 on Mac OS)  :-/

**Comment by gangstar902** [comment] 2017-08-14 08:23
me 2, atom 1.19 on win10

**Comment by robhuska** [comment] 2017-08-14 15:47
Mine does not crash, but typing SCSS/CSS has become super laggy. Unusable laggy even. :(

**Comment by jongeyer** [comment] 2017-08-15 06:56
I was seeing the same super lag on Atom 1.19.0 (OS 10.11.6), but just updated to Atom 1.19.1 and it seems to be resolved. Strange.

**Comment by gangstar902** [comment] 2017-08-15 09:23
@jongeyer that's weird, but seems solved

**Comment by sbritz** [comment] 2017-08-15 10:10
Unfortunately not, same problem with Atom 1.19.1 (OS 10.12.6)

**Comment by gangstar902** [comment] 2017-08-15 12:27
@sbritz u should try less files, maybe this module need indexing and ur working directory is so large that machine can't handle it

**Comment by robhuska** [comment] 2017-08-16 13:11
Lag not fixed for me. But I think I found out a little more about the lag. See my last comment in bug #333. It seems to happen depending on the style I use.

Atom 1.19.1
Latest OSX

**Comment by C-Bouthoorn** [comment] 2017-08-17 12:14
@robhuska Could you please specify which OS X is the latest? It might change in the future so it's best to keep version numbers absolute instead of relative 😉

**Comment by dschmidthawk** [comment] 2017-08-19 17:30
I am still having this issue, however I am on Windows 10 and I can't just disable Pigments, I have to uninstall to get Atom to stop freezing.

Atom 1.19.2 x64
Windows 10 v_1703 (OS Build 16251.0)

**Comment by 1c7** [comment] 2017-09-09 09:36
same, 

```
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.7 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.13
**Thrown From**: 'pigments' package vundefined


### Stack Trace

Failed to activate the pigments package

```
At Cannot read property 'length' of undefined

TypeError: Cannot read property 'length' of undefined
    at Function.Module._resolveLookupPaths (module.js:320:23)
    at Module._resolveFilename (module.js:461:31)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at requireCore (/packages/pigments/lib/pigments.coffee:295:7)
    at Object.patchAtom (/packages/pigments/lib/pigments.coffee:297:26)
    at Object.activate (/packages/pigments/lib/pigments.coffee:16:6)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:377:25
    at /Applications/Atom.app/Contents/Resources/app/src/config.js:644:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:835:35)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:621:25)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:236:20)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:386:18)
    at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app/src/package.js:84:32)
    at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:188:20)
    at HTMLButtonElement.enablementButtonClickHandler (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:361:31)
```

### Commands

```
     -3:32.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
  2x -1:52.6.0 core:undo (input.hidden-input)
     -1:49 core:select-all (input.hidden-input)
     -1:48.7.0 core:backspace (input.hidden-input)
     -1:44.1.0 core:copy (input.hidden-input)
     -1:42.6.0 core:paste (input.hidden-input)
     -1:42.3.0 core:save (input.hidden-input)
     -1:22.6.0 core:select-all (input.hidden-input)
     -1:20.3.0 core:backspace (input.hidden-input)
  2x -1:07.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-clock 0.1.13 
atom-css-comb 3.1.0 
atom-ternjs 0.18.2 
color-picker 2.2.5 
copy-path 0.4.1 
dark-flat-ui 1.2.4 
ember-snippets 2.1.0 
emmet 2.4.3 
file-icons 2.0.17 
git-control 0.8.2 
git-plus 7.9.3 
git-time-machine 1.5.9 
glacier-dark-ui 0.5.0 
go-config 1.2.4 
go-get 2.1.1 
gtk-dark-theme 0.1.4 
highlight-line 0.12.0 
highlight-selected 0.13.1 
jumpy 3.1.3 
language-haml 0.25.0 
linter 1.11.23 
linter-sass-lint 1.7.4 
linter-tidy 2.3.0 
markdown-writer 2.6.5 
merge-conflicts 1.4.5 
minimap 4.29.6 
navigator-go 1.1.3 
one-dark-vivid-syntax 1.7.1 
pacific-dark 0.5.0 
path-copy 0.14.0 
rails-snippets 2.12.0 
react 0.16.2 
script 3.14.1 
shadow 0.1.0 
split-diff 1.2.0 
symbol-gen 1.3.1 
todo-show 1.11.0 
zentabs 0.8.8 
```


```

**Comment by C-Bouthoorn** [comment] 2017-09-09 13:14
@1c7 Your message says "pigments package vundefined", which is probably a bug. Could you tell us the version you're using?

**Comment by 1c7** [comment] 2017-09-09 14:08
@C-Bouthoorn 
Sure, Thanks!
Atom version: 1.19.7
pigment version: not sure, I just uninstalled it, because it keep pop up error message

**Comment by C-Bouthoorn** [comment] 2017-09-22 20:39
Closing in favour of the [master post](https://github.com/abe33/atom-pigments/issues/351).

**Closed by C-Bouthoorn** 2017-09-22 20:39 UTC
Labels: bug
