### ISSUE TITLE
folders named "null" generated in project

### ISSUE THREAD

**Issue by Ctrl-J** [abe33/atom-pigments#69] opened 2015-08-09 20:16 UTC
After installing the pigments package I end up with folders titled "null" in various sub-folders of my project. These folders all contain files related to the pigments package (as seen in screenshots below). This occurs for me on both Windows 8.1 and Windows 10. Atom version is up to date (1.0.5), and pigments is at 0.9.3 

![image](https://cloud.githubusercontent.com/assets/6982652/9156692/36f0e8a0-3e98-11e5-9c65-a03c1b1e190e.png)

![image](https://cloud.githubusercontent.com/assets/6982652/9156705/616c03da-3e98-11e5-8172-52adf67deb28.png)

![image](https://cloud.githubusercontent.com/assets/6982652/9156707/7242013c-3e98-11e5-9b42-061f86382521.png)

**Comment by abe33** [comment] 2015-08-10 07:52
Hmm, thanks for the report, but I'm not really sure what happened, I never write anything, no directory, no files, I just read files from disk. 
To me, it looks like an issue with the package install process, like it has meddled your current working directory with the Atom's home path. And the fact that you have the color displayed means that pigments seems to work properly.

Can you reproduce this behavior by uninstalling/reinstalling pigments (and removing the `null` directory that was created)?

**Comment by Ctrl-J** [comment] 2015-08-10 13:13
Yeah, it's really strange. It doesn't always happen, but it's happened on multiple physical machines (work and home), as well as multiple operating systems (Windows 8.1 and 10.)

It also sometimes happens in multiple folders at the same time. Other times not at all. When it happens the folders are seemingly random.

The files generated are always the compiled output of your coffeescript code though. Only files from this repository end up in the folders.

I removed pigments last night, and reinstalled it after a machine reboot this morning and got the following:

![image](https://cloud.githubusercontent.com/assets/6982652/9172135/27646dd8-3f26-11e5-9341-6acc7d2ef28d.png)

**Comment by apvilkko** [comment] 2015-08-14 06:49
I can reproduce this also and it happens consistently so I have to keep pigments disabled. Windows 7, Atom 1.0.7, pigments 0.11.0.

Tried apm uninstall & apm install, the folders still appear.

The null folders seem to appear at the same locations where you edit & save a file.

**Comment by thomasjo** [comment] 2015-08-14 08:35
@Ctrl-J and @apvilkko, what other packages do you have installed? `apm list --installed`

**Comment by apvilkko** [comment] 2015-08-14 09:11
@thomasjo, my installed packages:

burn@0.1.0
color-picker@2.0.11
file-icons@1.6.3
git-tab-status@1.9.2
grunt-runner@0.11.0
hex@0.6.2
javascript-snippets@1.0.0
jshint@1.3.10
language-jade@0.6.2
linter@1.3.4
linter-pylint@0.2.2
minimap@4.12.3
no-caffeine-syntax@0.16.1
pigments@0.11.0
seti-syntax@0.4.0
Stylus@1.1.0
zentabs@0.8.6

**Comment by Ctrl-J** [comment] 2015-08-14 12:51
On my home machine:
├── advanced-new-file@0.4.3
├── ambiance@0.1.2
├── atom-alignment@0.12.1
├── atom-beautify@0.28.10
├── atom-material-syntax@0.2.3
├── atom-material-ui@0.5.20
├── atom-yeoman@0.3.11
├── autoprefixer@2.2.4
├── build@0.43.0
├── css-snippets@0.8.0
├── csscomb@0.3.1
├── csslint@1.1.3
├── emmet@2.3.12
├── isotope-ui@2.5.1
├── javascript-snippets@1.0.0
├── jshint@1.3.10
├── json-schema@0.1.11
├── lambda-syntax@0.5.0
├── lambda-ui@0.5.1
├── language-cshtml@0.1.1
├── language-rust@0.4.4
├── linter@1.3.4
├── omnisharp-atom@0.23.1
├── pigments@0.11.0
├── retro-gruvbox@1.0.4
└── steam-pirate-syntax@0.3.0

I'll post the plugins on my work machine in a bit.

**Comment by Skywalker13** [comment] 2015-08-21 11:30
Hello, I've the same problem

```
\.atom\packages (19)
├── atom-ternjs@0.7.1
├── color-picker@2.0.11
├── editorconfig@1.1.1
├── file-icons@1.6.7
├── git-plus@5.4.6
├── hex@0.6.2
├── highlight-selected@0.10.1
├── jsformat@0.9.0
├── language-batch@0.3.3
├── language-csharp@0.7.0
├── linter@1.4.3
├── linter-csslint@1.0.5
├── linter-js-yaml@1.1.1
├── linter-jscs@2.0.4
├── linter-jshint@1.1.5
├── merge-conflicts@1.3.5
├── pigments@0.11.0
├── react@0.12.6
└── todo-show@0.14.0
```

**Comment by abe33** [comment] 2015-08-22 10:02
Are you all on windows? I'm really at loss here, I don't reproduce it and I don't understand what could produce that side-effect. As I said, there's no code in pigments that write or compile anything on the filesystem, and I can't find a common denominator in the packages list you all provided.

**Comment by Skywalker13** [comment] 2015-08-22 10:17
I confirm, no problem under Linux. I've this null directory only under Windows

**Comment by batjko** [comment] 2015-08-25 08:52
Just to add, having countered this as well:
Using the the Package Cop package I could track the offending package down to Pigments as well, though of course I wouldn't know what causes this.

**Comment by abe33** [comment] 2015-08-25 10:54
I got my hands on a win7 computer, I hope I'll be able to reproduce that issue with it so I can fix it.

**Comment by PaulMorel** [comment] 2015-08-28 21:30
I'm on Windows 7 and I only seem to get this when I launch Atom via the command line.

Ex: Running `cmd` in my project folder and launching Atom via the `atom .` command to open it in the current folder.

**Comment by peterblazejewicz** [comment] 2015-08-31 20:54
+1 Win8.1

**Comment by C-Bouthoorn** [comment] 2017-01-14 22:33
Now that we're more than 1.5 years later, I think this is fixed. Closing because of that reason.

**Closed by C-Bouthoorn** 2017-01-14 22:33 UTC
Labels: bug, more-information-needed
