### ISSUE TITLE
slow

### ISSUE THREAD

**Issue by NickWald** [abe33/atom-pigments#188] opened 2016-05-22 17:24 UTC
pigments has been making atom VERY slow lately. I cant even move my mouse when pigments is enabled. I guess no pigments right now. 👎

**Comment by abe33** [comment] 2016-05-23 07:58
Yeah, I noticed that too on master (I guess you're running master or beta?). It seems linked to the introduction of display layers ans the fact that I don't use native decoration to render the color markers.

I submitted a PR on atom to extend the current highlight decoration with a parameter that would allow me to switch background, outline and underline decorations on native decorations (see atom/atom#11787). But I can't guarantee if and when it'll land on master. For the time being I'm looking for a way to fix that using monkey patching.

**Comment by antoinebeaumont** [comment] 2016-05-24 14:54
Same problem here : in a 2k lines CSS file with ~200 (background-/border-)color rules, every edit take 4-5sec
Atom: 1.7.4 - Pigments : 0.26.3

**Comment by abe33** [comment] 2016-05-26 10:21
I just push version 0.27 that should help on that matter, 0.26 introduced a regression where every markers, not just the ones that are visible at one time, were added in the editor, which was penalizing the update routine a lot. That's now fixed. Also, the latest version introduce new decoration types that use native decoration instead of custom ones, performances should be slightly better with them, but they may have some glitches that didn't foresee.

**Comment by NickWald** [comment] 2016-05-26 18:14
@abe33 Native-Background fixes it 100%! Thank you so much

**Comment by antoinebeaumont** [comment] 2016-05-27 07:57
Works very very better ! Thank you !

**Comment by glen-84** [comment] 2016-06-09 18:02
I'm using `native-square-dot` and it's taking like 5-6 seconds to change a colour after I update it. This combined with other performance issues means that I'll have to keep this plug-in disabled. :disappointed:

**Comment by Samji** [comment] 2016-10-25 16:19
Still happening @abe33 - open a file and the pigments appear in the wrong location on screen - fixed by scrolling - then atom slows to a crawl. (version 0.37.0).

**Comment by abe33** [comment] 2016-10-26 08:24
@Samji Which kind of decorations are you using?

**Comment by Samji** [comment] 2016-11-05 16:42
sorry for the long wait time - I'm using circles at the end of the line

**Comment by abe33** [comment] 2016-11-07 15:56
@Samji, no pb, are you using `dot` or `native-dot` ones? if the former try the latter it uses native decorations and are clearly much 🐎.

**Comment by Samji** [comment] 2016-11-07 16:52
excellent fix thanks @abe33

**Comment by C-Bouthoorn** [comment] 2017-01-14 22:23
Closed because it seems fixed.

**Comment by glen-84** [comment] 2017-01-15 09:11
Not for me.

It still takes a long time to change a colour, and while it's figuring that out the cursor stops flashing, like the thread is blocked.

**Comment by C-Bouthoorn** [comment] 2017-01-15 09:12
In that case I'll reopen it until we have a fix

**Comment by dnagroove** [comment] 2017-05-13 14:36
This bug is still going strong, any news?

**Comment by dmbdesignpdx** [comment] 2017-07-26 18:35
I'm using version **0.39.1** and experiencing long delays in typing.

Context: My Sass file is ~1000 lines of code and I've been using the Native Square Dot.

Some behavior and scenarios I've noticed so far:
- Typing is _extremely_ laggy towards the **bottom** of the file and not laggy at the top of the file; it takes anywhere from 1 to 3 seconds for the character(s) typed to appear
- Switching the Marker Type to any other type seems to fix it for the instance Atom is open, even switching back to Native Square Dot seems to be ok; but if Atom closes and starts back up with Native Square Dot it's laggy again
- Switching to Native Background closing and starting Atom up with it seems to be fine

Let me know if you need any more info or testing

**Comment by vettorazi** [comment] 2017-08-07 21:15
same here! i am about to change from atom! i am working all week in the notepad!

**Comment by birdspider** [comment] 2017-08-14 10:52
I do not really need pigments, had I installed for testing. But while investigating some "lag" I think it to be the culprit.

![pigments-slow](https://user-images.githubusercontent.com/370960/29268945-59bcc386-80ef-11e7-9d26-673ca4c03ef6.png)

**Comment by C-Bouthoorn** [comment] 2017-09-22 20:40
Closing in favour of the [master post](https://github.com/abe33/atom-pigments/issues/351).

**Closed by C-Bouthoorn** 2017-09-22 20:40 UTC
Labels: bug
