### ISSUE TITLE
dot, square-dot position

### ISSUE THREAD

**Issue by cortauri** [abe33/atom-pigments#191] opened 2016-05-25 20:20 UTC
dot and square-dot marker types margin-left value ist to small, markers actually touching the code in Atom 1.7.4

**Comment by DanielPintilei** [comment] 2016-05-26 07:12
Same here. Setting `margin-left` to 15-20px for `.dot` works for me.

**Comment by abe33** [comment] 2016-05-26 10:10
Hi there, can you confirm whether you still get that issue with 0.27?

**Comment by abe33** [comment] 2016-05-26 10:23
Also, it's a duplicate of #178

**Comment by DanielPintilei** [comment] 2016-05-26 10:34
Looks better with 0.27 but it's not fixed, the dot covers the `;`. Changing `transform: translate(50%, -50%);` to `transform: translate(100%, -50%);` works for me.

**Comment by abe33** [comment] 2016-05-26 10:42
@DanielPintilei And with the `native-dot` type instead?

**Comment by DanielPintilei** [comment] 2016-05-26 10:49
Setting the marker to native dot gives me and error.
".../.atom/packages/pigments/lib/color-buffer-element.coffee:288"

**Comment by danny505d** [comment] 2016-05-26 19:19
I was also getting this error (even after the upgrade to 0.27). I uninstalled and re-installed, and seemed to clear it up for me without changing anything else.

**Comment by defking** [comment] 2016-05-27 13:17
Re-installing the plugin fixed the problem.

**Comment by DanielPintilei** [comment] 2016-05-27 13:42
Looks good in 0.27.1

**Comment by SentientSeven** [comment] 2016-05-27 13:44
0.27.1 fixed this for me, thanks @abe33 !

**Closed** 2016-05-27 22:48 UTC
Labels: bug
