### ISSUE TITLE
right click error in editor

### ISSUE THREAD

**Issue by zhangby01** [abe33/atom-pigments#387] opened 2018-03-16 06:44 UTC
ATOM 1.234.1 ia32

pigments 0.40.2

err:

```
TypeError: Cannot read property 'NaN' of undefined
    at TextEditorComponent.renderedScreenLineForRow (C:\Users\Me\AppData\Local\atom\app-1.24.1\resources\app\src\text-editor-component.js:963:37)
    at TextEditorComponent.screenPositionForPixelPosition (C:\Users\Me\AppData\Local\atom\app-1.24.1\resources\app\src\text-editor-component.js:2399:33)
    at HTMLElement.screenPositionForPixelPosition (C:\Users\Me\AppData\Local\atom\app-1.24.0\resources\app.asar\src\text-editor-element.js:250:32)
    at HTMLElement.ColorBufferElement.screenPositionForMouseEvent (file:///C:/Users/Me/.atom/packages/pigments/lib/color-buffer-element.coffee:429:22)
    at HTMLElement.ColorBufferElement.colorMarkerForMouseEvent (file:///C:/Users/Me/.atom/packages/pigments/lib/color-buffer-element.coffee:415:17)
    at Object.colorMarkerForMouseEvent (file:///C:/Users/Me/.atom/packages/pigments/lib/pigments.coffee:221:25)
    at Object.shouldDisplayContextMenu (file:///C:/Users/Me/.atom/packages/pigments/lib/pigments.coffee:215:5)
    at Object.atom.contextMenu.add.atom-text-editor.shouldDisplay (file:///C:/Users/Me/.atom/packages/pigments/lib/pigments.coffee:111:36)
    at ContextMenuManager.module.exports.ContextMenuManager.cloneItemForEvent (C:\Users\Me\AppData\Local\atom\app-1.24.1\resources\app\src\context-menu-manager.js:167:25)
    at ContextMenuManager.module.exports.ContextMenuManager.templateForEvent (C:\Users\Me\AppData\Local\atom\app-1.24.1\resources\app\src\context-menu-manager.js:100:39)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\Me\AppData\Local\atom\app-1.24.1\resources\app\src\context-menu-manager.js:189:33)
    at WindowEventHandler.handleDocumentContextmenu (C:\Users\Me\AppData\Local\atom\app-1.24.1\resources\app\src\window-event-handler.js:251:44)
```

**Comment by C-Bouthoorn** [comment] 2018-03-18 13:09
Duplicate of https://github.com/abe33/atom-pigments/issues/377 and https://github.com/abe33/atom-pigments/issues/354

**Closed by C-Bouthoorn** 2018-03-18 13:09 UTC
