### ISSUE TITLE
Not all pigments displaying 

### ISSUE THREAD

**Issue by kazik56** [abe33/atom-pigments#409] opened 2018-09-14 17:30 UTC
Atom v1.30.0
Pigments v0.40.2
Windows 10.0.17134 Build 17134

Pigments don't display next to all colors in stylesheet if marker type is chosen as 'dot'. When the marker type is 'background' they all display correctly.

Marker type: background. Everything's correctly displaying.
![pigments_bug_background](https://user-images.githubusercontent.com/24499074/45565593-7c263b00-b843-11e8-8f5a-da0356c50f0f.PNG)
Marker type: dot. Some (or in this case most) dot markers are missing.
![pigments_bug_dot](https://user-images.githubusercontent.com/24499074/45565592-7c263b00-b843-11e8-8c2d-2493e37d20eb.PNG)

**Comment by C-Bouthoorn** [comment] 2018-09-19 12:14
This seems to be related to https://github.com/abe33/atom-pigments/issues/369 in that they both happen after line 48.

**Comment by C-Bouthoorn** [comment] 2019-03-12 22:20
Duplicate of #369

**Closed by C-Bouthoorn** 2019-03-12 22:20 UTC
