### ISSUE TITLE
Uncaught Error: kill EPERM

### ISSUE THREAD

**Issue by chuz** [abe33/atom-pigments#423] opened 2019-03-29 03:30 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package 0.40.2

### Stack Trace

Uncaught Error: kill EPERM

```
At events.js:183

Error: kill EPERM
    at _errnoException (util.js:1024:11)
    at ChildProcess.kill (internal/child_process.js:395:26)
    at Task.t.exports.Task.terminate (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:14:38077)
    at ColorBuffer.module.exports.ColorBuffer.terminateRunningTask (/packages/pigments/lib/color-buffer.coffee:166:35)
    at /packages/pigments/lib/color-buffer.coffee:33:8
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:1172354)
    at Emitter.emit (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:1173795)
    at disposables.add.displayLayer.onDidChange.e (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:6510)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:1172354)
    at Emitter.emit (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:1173795)
    at DisplayLayer.emitDeferredChangeEvents (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:14:91874)
    at TextBuffer.emitDidChangeTextEvent (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:504278)
    at TextBuffer.transact (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:492297)
    at TextEditor.transact (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:24215)
    at TextEditor.moveCursors (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:33112)
    at TextEditor.setCursorScreenPosition (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:30265)
    at TextEditorComponent.didMouseDownOnContent (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:95794)
```

### Commands

```
  3x -1:32.7.0 core:move-right (input.hidden-input)
     -1:31.2.0 editor:newline (input.hidden-input)
  2x -1:27.9.0 core:backspace (input.hidden-input)
     -1:25.4.0 core:delete (input.hidden-input)
 29x -1:24.3.0 core:move-right (input.hidden-input)
     -1:20.3.0 editor:newline (input.hidden-input)
  4x -1:17.4.0 core:backspace (input.hidden-input)
     -1:13.7.0 core:delete (input.hidden-input)
  3x -1:12.9.0 core:move-right (input.hidden-input)
     -1:11.5.0 editor:newline (input.hidden-input)
     -1:07.9.0 core:delete (input.hidden-input)
 26x -1:07.5.0 core:move-right (input.hidden-input)
  2x -1:02.1.0 core:save (input.hidden-input)
  2x -0:28.6.0 core:delete (input.hidden-input)
     -0:20.8.0 pane:close (span.name.icon.icon-file-directory)
     -0:11.5.0 tree-view:remove (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
minimap 4.29.9 
minimap-pigments 0.2.2 
pigments 0.40.2 
pretty-html 1.0.0 
pretty-json 2.0.3 
```

**Comment by C-Bouthoorn** [comment] 2019-06-11 15:35
Duplicate of #418 #413 #411 #392 #373 #359

**Closed by C-Bouthoorn** 2019-06-11 15:35 UTC
