### ISSUE TITLE
Colors not showing in my Atom?

### ISSUE THREAD

**Issue by NaomiMadeIt** [abe33/atom-pigments#247] opened 2016-11-10 05:45 UTC
Been using Pigments on my Atom for a while now, but it hasn't seemed to been working. I can't say exactly when it stopped working for me, but it's been a little while now. I was just wondering why? Maybe my atom (1.12.0) is too old? I'm using Windows 7 currently and the version of Pigments I have now is 0.37.0. I've deleted the package and reinstalled just to be sure, still nothing. It just won't work and I don't really know any other package of the sort.  It's super helpful to see what colors I'm working with as I go through, so it's been a pain that it hasn't been. I know it's not just the Pigment package as a whole because I use it at school, but there we have Windows10. Any way I can get this to work? Or maybe someone has suggestions as to which packages I can use to substitute this? (Also I'm new to GitHub, so forgive me if I'm using this wrong! Literally just made my account.) Thank you for reading.

**Comment by dodekeract** [comment] 2016-11-11 14:39
Same here with `1.12.0` on macOS Sierra.

**Comment by maciejbialek** [comment] 2016-11-12 02:06
Win10, Atom 1.12.2, Pigments 0.38 and the same problem :( HELP!

**Comment by C-Bouthoorn** [comment] 2016-11-12 10:27
Could you try using Atom Beta? Pigments does work for me on that version

**Comment by dodekeract** [comment] 2016-11-12 10:35
@maciejbialek Can you try to delete the package and install 0.37? That fixed it for me.

**Comment by maciejbialek** [comment] 2016-11-13 00:45
0.37 works! 👍

**Comment by thezoid** [comment] 2016-11-13 12:25
Do NOT any colors. here is a video: https://youtu.be/u1YGS8Hr5d4
My installed packages: https://i.imgur.com/g5kPIaR.png

I have had atom with pigments installed for months and I've never noticed any change.

**Comment by thezoid** [comment] 2016-11-13 12:32
uhhhh... I don't know how or why but I installed the webbox-color package while pigments was installed, it looked really funny so i uninstalled webbox color, restarted atom and pigments is working now... ? ! ?

**Comment by onomori** [comment] 2016-11-13 15:51
Having the same issue on the latest stable Atom in Windows 7. Tried re-installing Pigments but a note saying "**Version 0.37.0 is not the latest version available for this package, but it's the latest that is compatible with your version of Atom**" appears. Checking on the package list, Pigments 0.38.0 is listed installed although it doesn't work as intended at all. It messes up the text that it should be changing like so.

![1](https://cloud.githubusercontent.com/assets/16868065/20246828/5b16602e-a9fa-11e6-9313-4d8b09d71527.png)

**Comment by thezoid** [comment] 2016-11-13 16:03
Did you try installing and uninstalling a different package? Else uninstall pigment, put the 0.37 in the folder, restart atom, then if it still doesn't work try installing and uninstalling a different package again.

**Comment by onomori** [comment] 2016-11-13 16:18
Should've tried first before hitting that comment button: Just installed 0.37.0 through apm and looks like everything's working fine now without having to uninstall other packages.

**Comment by abe33** [comment] 2016-11-21 12:06
Hi guys, sorry for the late reply. It seems that in some condition `apm` isn't honoring the `engine` field in package.json. v0.38 is supposed to be only available starting with Atom 1.13 (which removes shadow DOM) but if you had it installed on 1.12 and prior version you won't see anything as it won't target the shadow DOM. 

Are you by chance using [auto-update-packages](https://atom.io/packages/auto-update-packages) as it appears it installs updates without taking care of the version constraints.

**Comment by dodekeract** [comment] 2016-11-21 13:27
@abe33 mine broke after restoring my backup via `sync-settings`.

**Comment by ag-coder** [comment] 2016-11-26 11:52
"mine broke after restoring my backup via sync-settings" same here

**Comment by RyanRoberts** [comment] 2016-11-27 22:04
Problems here too, even after a completely clean reinstall and pigments as the only community package. _Some_ colors do show up correctly but if I edit them or add new colors it fails to work.

Atom version: 1.12.5
Pigments version: 0.37.0
macOS version: 10.12.1 (16B2555)

**Comment by savimat** [comment] 2016-11-30 03:22
I have it working again after downgrading from 0.38 to 0.37. Using Atom 1.12.6 and macOS 10.12.1.

**Comment by yuzhakovvv** [comment] 2016-12-02 19:47
Fixed this one by Uninstalling v0.38 and `apm install pigments@0.37.0` . Using Atom 1.12.6 and Windows 10.

**Comment by basistam** [comment] 2016-12-09 20:58
Had same issue. Looks like bug in current atom version (1.12.7). In current beta (1.13) it is working properly.

**Comment by olamedia** [comment] 2016-12-12 05:36
Confirming, `apm install pigments@0.37.0` fixed the problem. (Installed fresh copy of Atom 1.12.7 from atom.io website, Linux Mint 17.3 Rosa/Ubuntu Trusty)

**Comment by C-Bouthoorn** [comment] 2017-01-14 21:53
Now that Atom 1.13 is on stable, I guess this isn't a problem anymore, and I'll close it for that reason. If anyone still has this issue, please let us know!

**Closed by C-Bouthoorn** 2017-01-14 21:53 UTC
Labels: bug, more-information-needed

**Comment by madranet** [comment] 2017-01-18 17:17
I've just run into this problem myself. 

```
Mac OSX 10,11,16
Atom 1,13,0
Pigments 0,38,0
```

Not sure exactly when it happened as I've applied various updates [both to Atom and installed packages] since I last edited any CSS files. 

Toggling  `Disable/Enable` in the Pigments Settings window works to get Pigments displaying colours again, without having to uninstall/reinstall anything. However it doesn't persist through a restart, so I have to do it again each time I relaunch Atom, to 'jump-start' Pigments.

**Comment by socialmedialabs** [comment] 2017-11-25 13:58
Same here.

`macOS 10.12.6 (16G1036)
Atom 1.22.1
Pigments 0.40.2`

**Please note: colors will be parsed up until line number 48, any line beyond line number 48 pigments will not detect any color.**

I have restarted Atom editor several times, also tried installing previous versions of pigments.

**Comment by Jfaler** [comment] 2017-12-02 00:06
@socialmedialabs I have the exact same problem.

**Comment by C-Bouthoorn** [comment] 2017-12-02 12:23
@Jfaler A new issue has already been created, so you don't have to :smile:

**Comment by natty4GitHub** [comment] 2018-05-03 14:31
It's been about a week and i see that pigmentation is missing lately on my IDE however the same file looks just fine on Visual Studio Code. Any idea? suggestions ?
<img width="469" alt="screen shot 2018-05-03 at 10 27 52 am" src="https://user-images.githubusercontent.com/9864568/39582908-ef90f832-4ebc-11e8-9f4e-865b293f511e.png">

**Comment by C-Bouthoorn** [comment] 2018-05-05 09:29
@natty4GitHub To me it seems you're just missing a double quotation mark somewhere. Besides, I don't see anything that's supposed to be a colour there either.

**Comment by Piplopp** [comment] 2018-06-28 14:59
Hello,
I don't have any colors anymore from the pigments package, the "disable/enable" solution works for me but I have to do it everytime I open atom

My pigments version is 0.40.2; And my Atom's is 1.27.2.
Awesome addon still :+1:
