### ISSUE TITLE
Failed to activate the pigments package for Atom editor

### ISSUE THREAD

**Issue by bengoldman** [abe33/atom-pigments#344] opened 2017-09-05 15:02 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.4 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.11.3
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package 0.39.1

### Stack Trace

Failed to activate the pigments package

```
At Cannot find 'highlights-component' in the require cache.

Error: Cannot find 'highlights-component' in the require cache.
    at requireCore (/packages/pigments/lib/pigments.coffee:310:19)
    at Object.patchAtom (/packages/pigments/lib/pigments.coffee:312:26)
    at Object.activate (/packages/pigments/lib/pigments.coffee:16:6)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:603:52)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:843:36
```

### Commands

```
```

### Non-Core Packages

```
atom-material-ui 1.3.10 
aurora-theme 1.2.2 
dracula-syntax 2.0.5 
dracula-theme 2.0.0 
emmet 2.4.3 
emmet-simplified 2.5.0 
gloom 0.6.4 
jquery-snippets 11.0.0 
monokai 0.24.0 
monokai-dark 1.3.0 
nord-atom-ui 0.11.0 
pigments 0.39.1 
ramda-syntax 1.0.4 
wp-snippets 0.2.10 
```

**Comment by C-Bouthoorn** [comment] 2017-09-05 20:29
Duplicate of #341 #338 #335 #334 #329 #328 #318 #314 #201 
Solution: Update Pigments

**Closed by C-Bouthoorn** 2017-09-05 20:29 UTC

**Comment by liwenli111** [comment] 2017-09-07 12:15
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.6 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package 0.39.1


### Stack Trace

Failed to activate the pigments package

```
At Cannot find 'highlights-component' in the require cache.

Error: Cannot find 'highlights-component' in the require cache.
    at requireCore (/packages/pigments/lib/pigments.coffee:310:19)
    at Object.patchAtom (/packages/pigments/lib/pigments.coffee:312:26)
    at Object.activate (/packages/pigments/lib/pigments.coffee:16:6)
    at Package.module.exports.Package.activateNow (/Applications/Atom-1.19.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom-1.19.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom-1.19.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom-1.19.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom-1.19.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom-1.19.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom-1.19.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/Applications/Atom-1.19.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom-1.19.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom-1.19.app/Contents/Resources/app/src/package-manager.js:603:52)
    at /Applications/Atom-1.19.app/Contents/Resources/app/src/atom-environment.js:843:36
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
atom-beautify 0.30.5 
atom-live-server 2.1.2 
atom-react-autocomplete 0.1.10 
atom-ternjs 0.18.3 
autocomplete-paths 1.0.5 
autoprefixer 3.7.1 
block-comment 0.4.3 
browser-plus 0.0.98 
busy-signal 1.4.3 
color-picker 2.2.5 
comment 0.6.1 
csslint 1.1.5 
docblockr 0.11.0 
emmet 2.4.3 
file-icons 2.1.11 
hyperclick 0.1.3 
jquery-snippets 11.0.0 
js-hyperclick 1.11.0 
jshint 1.8.6 
language-javascript-jsx 0.3.7 
language-vue 0.23.1 
language-vue-component 0.5.0 
linter 2.2.0 
linter-csslint 1.3.4 
linter-jshint 3.1.5 
linter-ui-default 1.6.7 
minimap 4.29.6 
minimap-quick-highlight 1.0.1 
open-html-in-browser 0.2.0 
open-in-browser 0.5.2 
package-sync 1.1.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.5 
quick-highlight 0.10.0 
react-es6-snippets 0.3.0 
react-snippets 0.9.0 
script 3.15.0 
sublime-block-comment 0.5.1 
terminal-plus 0.14.5 
tool-bar 1.1.0 
tool-bar-main 0.0.10 
vue-snippets 0.6.0 
vue2-autocomplete 0.1.0-alpha.4 
```

**Comment by hjchdf** [comment] 2017-09-19 05:24
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package 0.39.1


### Stack Trace

Failed to activate the pigments package

```
At Cannot find 'highlights-component' in the require cache.

Error: Cannot find 'highlights-component' in the require cache.
    at requireCore (/packages/pigments/lib/pigments.coffee:310:19)
    at Object.patchAtom (/packages/pigments/lib/pigments.coffee:312:26)
    at Object.activate (/packages/pigments/lib/pigments.coffee:16:6)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.20.0/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.20.0/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.20.0/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.20.0/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.20.0/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.20.0/resources/app/src/package-manager.js:645:40)
    at ~/AppData/Local/atom/app-1.20.0/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.20.0/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (~/AppData/Local/atom/app-1.20.0/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (~/AppData/Local/atom/app-1.20.0/resources/app/src/package-manager.js:603:52)
    at ~/AppData/Local/atom/app-1.20.0/resources/app/src/atom-environment.js:843:36
```

### Commands

```
     -0:32.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -0:11.1.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-monokai-flat.theme-atom-dark-ui)
```

### Non-Core Packages

```
atom-csscomb 2.0.4 
atom-html-preview 0.1.22 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.7 
minimap 4.28.2 
monokai-flat 1.0.1 
pigments 0.39.1 
sync-settings 0.8.3 
vim-mode-plus 0.93.0 
```

**Comment by C-Bouthoorn** [comment] 2017-09-20 15:28
@liwenli111 Did the answers which I gave (updating Pigments) fix it for you?

**Comment by studiomantis** [comment] 2017-09-28 16:19
Update the plugin and it will work (I had right now the issue, and when I saw the upadate, I did and solved the issue)

**Comment by GabiArzu** [comment] 2017-09-30 10:57
I'm getting the same error even after the update, the error is on the launch of atom and the package wont work.

**Comment by C-Bouthoorn** [comment] 2017-09-30 11:42
@GabiArzu Seems unlikely. Did you:
1) update Pigments to its latest version (0.40.2)?
2) update Atom to its latest version (1.20.1)?
3) restart Atom?

**Comment by GabiArzu** [comment] 2017-10-01 17:38
Yes, all of the above :

Atom 1.20.1 (if im not wrong), Uninstall and reinstall pigment, restart for the computer, still same issue

**Comment by emitche** [comment] 2017-10-03 14:09
I was having this problem and the newest pigments package does work for me. Here are some steps to install the newest package.

I have Atom version 1.20.1.

To update pigments, in a terminal, I typed in `apm list`. Pigments was listed in the community packages section. It was at `0.39.1`. I then did `apm install pigments` to install to the new version of pigments. I checked the version in `apm list` and saw that my pigments was updated.

I then restarted Atom and pigments works again.

More info on APM is over here. The `apm` command runs in the terminal.

**Comment by emitche** [comment] 2017-10-03 14:11
@GabiArzu The above may not fix your issue, as it sounds like you've already done similar steps already. But I've added the above in case someone else needs steps, as I certainly did. Thanks. I hope you get pigments working again soon.

**Comment by sajelgoel** [comment] 2017-10-06 16:12
Try this: [https://youtu.be/dRhXjz7-Rro](url)

**Comment by harryfinn** [comment] 2017-10-19 08:44
Thanks @emitche, update manually via `apm` worked for me, have been without pigments for a few weeks after an atom update, was really starting to miss my colourful stylesheets! 

Strange that Atom didn't detect an update for pigments via the UI though...

**Comment by timfrio** [comment] 2017-11-14 15:15
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0 ia32
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package 0.37.0


### Stack Trace

Failed to activate the pigments package

```
At Cannot read property 'length' of undefined

TypeError: Cannot read property 'length' of undefined
    at Function.Module._resolveLookupPaths (module.js:320:23)
    at Module._resolveFilename (module.js:461:31)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.22.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.22.0/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.22.0/resources/app/src/native-compile-cache.js:66:33)
    at requireCore (/packages/pigments/lib/pigments.coffee:295:7)
    at Object.patchAtom (/packages/pigments/lib/pigments.coffee:297:26)
    at Object.activate (/packages/pigments/lib/pigments.coffee:16:6)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.22.0/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.22.0/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.22.0/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.22.0/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.22.0/resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.22.0/resources/app/src/package-manager.js:690:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.22.0/resources/app/src/package-manager.js:665:36)
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.22.0/resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.22.0/resources/app/src/package-manager.js:663:23)
    at PackageManager.activate (~/AppData/Local/atom/app-1.22.0/resources/app/src/package-manager.js:646:50)
    at ~/AppData/Local/atom/app-1.22.0/resources/app/src/atom-environment.js:854:36
```

### Commands

```
     -1:58.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-clock 0.1.3 
bookmark-panel 1.0.0 
browser-plus 0.0.87 
emmet 2.4.3 
file-icons 2.0.14 
github-utils 1.6.0 
minimap 4.25.7 
minimap-bookmarks 0.4.2 
minimap-highlight-selected 4.5.0 
open-in-github-app 0.2.6 
pigments 0.37.0 
Remote-FTP 1.1.3 
```

**Comment by C-Bouthoorn** [comment] 2017-11-19 13:01
@timfrio It seems like that error is not related to this one. Could you try updating Pigments? If that doesn't work, could you move your comment to a separate issue? Thanks
