### ISSUE TITLE
Rendering issue when editing themes using --dev mode.

### ISSUE THREAD

**Issue by JesseLeite** [abe33/atom-pigments#124] opened 2015-12-22 15:13 UTC
I've noticed some really funny rendering when pigments is enabled, and I'm editing an Atom theme using `atom --dev` mode.  This is what is happening...

I have a colours.less file, and a base.less file in my theme.  This is what colors.less looks like:
![example](http://b3.ms/Oq5nR4jj90wB)

If I switch tabs and save base.less, then switch back to colors.less, I get this:
![wat](http://b3.ms/Y2g9Kl0eA0l3)

Yikes :)  I'm not sure if this ever happens without `--dev` mode, but I'll keep my eye open.  It can be remedied by CMD-S saving colors.less, which prompts pigments to re-render.  If this only happens in `--dev` mode, then it doesn't affect most of users.  However, pigments is REALLY helpful when creating an Atom theme, and it's really annoying to deal with when theming.  Thoughts on why this might be happening?

**Comment by abe33** [comment] 2015-12-22 15:19
I guess you're on running Atom on master? I've opened an issue on atom for that matter (atom/atom#10051). I still haven't found a good way to reproduce this issue so that I can write a test for it and submit a patch.

**Comment by JesseLeite** [comment] 2015-12-22 15:23
Yes on master :)  I notice atom/atom#10051 describes "invalid x position".  However, on top of x position, pigments doesn't render the marker/background color either.  Why might x position be affecting marker/background rendering?

**Comment by abe33** [comment] 2015-12-22 15:34
>  Why might x position be affecting marker/background rendering?

Because the region div's left and width property are actually 0 the marker's background isn't visible, but as no overflow is applied the text is still visible

**Comment by JesseLeite** [comment] 2015-12-22 15:36
Ah interesting.  Thanks!  Feel free to close this, if you'd rather just deal in the atom issue thread.

**Comment by abe33** [comment] 2015-12-22 15:40
I think I'll leave it open so that people experiencing the same issue can find it more easily.

**Comment by abe33** [comment] 2015-12-22 16:53
@JesseLeite It should be fixed in v0.19.4 by making sure the markers are rendered on a new animation frame. Let me know if you still get this issue.

**Comment by JesseLeite** [comment] 2015-12-22 17:02
Oh nice thanks!  It was in your code, not Atom core?  Also, which master stream release should 0.19.0 be included in?

**Comment by abe33** [comment] 2015-12-22 17:32
> Oh nice thanks! It was in your code, not Atom core? 

There's is a regression in Atom, but I found a way to workaround it.

> Also, which master stream release should 0.19.0 be included in?

I'm not sure what you mean, are you talking about Pigments or Atom?

**Comment by JesseLeite** [comment] 2015-12-22 17:33
>I'm not sure what you mean, are you talking about Pigments or Atom?

Oh it's just a package update.  I'll test it out now, thanks!

**Comment by JesseLeite** [comment] 2015-12-22 17:40
Hmm, just updated to 0.19.4, then restarted Atom completely.  Still having problem when running `atom --dev`.  Here's a screencast:

![screencast](http://g.recordit.co/KMetPgr5Fj.gif)

I'm triggering the issue by saving one file, then switching tabs to other file.  Then I fix rendering by saving that file.

**Comment by abe33** [comment] 2015-12-22 18:02
Hmm, I'm not reproducing. 
I see that there's the blue squirrel at the right bottom of Atom, which version are you running?

**Comment by JesseLeite** [comment] 2015-12-22 18:25
This is version 1.3.2.  It doesn't happen when running Atom normally.  It only happens when I open Atom in dev mode using this command: `atom --dev`

Trying to figure out how to open 1.4.0 beta using --dev mode, then I'll test there as well.

**Comment by JesseLeite** [comment] 2015-12-22 18:32
Oh found an option in menu (View > Developer > Open in Dev Mode).  Here's same thing happening in 1.4.0-beta3 running in --dev mode:

![screencast](http://g.recordit.co/zkJvOxAMzX.gif)

**Comment by abe33** [comment] 2015-12-22 18:34
I'm not really seeing what could go wrong here, I'll reopen and investigate to see if I can find a way to reproduce that behaviour.

**Comment by JesseLeite** [comment] 2015-12-22 18:40
No problem, thank you for your time and replies as well!

I just tried using Package Cop to disable all 3rd party packages.  Then I enabled only Pigments, and reloaded window just to be sure.  Still having same issue.  Just wanted to be sure another 3rd party package isn't interfering.  And again, it only seems to happen in --dev mode.  Hope it helps.

**Comment by abe33** [comment] 2015-12-23 08:49
Looks I didn't checked properly, I reproduce that on a project in dev mode, and not in normal mode. Maybe there's some kind of extra delay in dev mode when rebuilding the lines of the editor that make my fix pointless in dev mode.

**Comment by abe33** [comment] 2015-12-23 10:05
@JesseLeite I just published a new version, let me know if it solves things for you. I force a rerender of the markers that have an empty region. In my tests it seems to fix this issue.

**Comment by JesseLeite** [comment] 2015-12-23 13:31
Before I updated to 0.19.5, I did one more test this morning and noticed it didn't happen even on 0.19.4.  I played with things a bit, and realized I had a different theme active.  I guess it's not just --dev mode, but it's --dev mode when editing a theme I have active.  For example, I'm making [this theme](https://atom.io/themes/an-old-hope-syntax), and had it both active and in --dev mode so that I could see styling changes in realtime as I edit the theme itself.  Anyway, that information aside...

Just updated to 0.19.5, and tested in both Atom 1.3.2 and 1.4.0-beta.  Seems great now!  Thank you :heart:

**Comment by JesseLeite** [comment] 2015-12-23 13:33
Also Merry Christmas! :christmas_tree:

**Comment by abe33** [comment] 2015-12-23 13:43
Interesting, I'll give it a try to see what could go wrong. 

Merry Christmas to you too :)

**Comment by JesseLeite** [comment] 2015-12-23 13:45
Yeah, I mean you fixed the issue already with that last update... but might help if you knew the cause more specifically :)

**Closed** 2016-01-11 17:44 UTC
