### ISSUE TITLE
Slow down and freeze entire editor when open html file

### ISSUE THREAD

**Issue by juanfernandoe** [abe33/atom-pigments#121] opened 2015-12-13 21:36 UTC
I hope it helps to solve the problem, 

my editor was freezing every time i open a html file, after i disable pigments everything works fine.

**Comment by abe33** [comment] 2015-12-13 22:36
Hi @juanfernandoe, can you provide a sample so that I can reproduce the issue? There might be some edge cases I haven't considered, but without reproduction I won't be able to narrow down the issue and fix it.

**Comment by c9dd** [comment] 2015-12-16 16:48
I have the same issue here. How do I give you what you need so you can reproduce the issue?

**Comment by abe33** [comment] 2015-12-16 22:49
If you're working on a public project you can just provide me the link to it. If it's a private project, the best would be to provide the smallest HTML sample that triggers this issue. One important thing to note here: as Pigments works on a whole project, problem can arise in file due to the context, but not necessarily if the same file opened outside the project's context, that's why having a sample project is always more telling than just a single file. But I believe that for an HTML file the project is not necessary (variables defined in Sass/Less/Stylus files shouldn't play when parsing colors in a HTML file).

Also, if you know a bit how to use the devtools (and given you can still use them), you try profiling the moment it freeze and post the results somewhere so I can have a look at it.

**Comment by yoohahn** [comment] 2015-12-22 10:23
I can see it with only 1 file open that is completely empty. As soon as I start typing Atom freezes for like ~500ms and then it's back again. And this happens over and over again. It worked before I did an update (I am pretty sure that I was using v0.19.1 before, but will try to down grade during the day to see if it gets better)

I have not seen this on my Mac at home, but at work I am using Windows 10 and there I have the issue.

**Comment by meetjey** [comment] 2017-01-17 10:05
+1 
Windows 10, Atom 1.13.0 & pigments 0.38.0
Slow down after typing or moving cursor on every files.
When module is disabled, no more problems.

**Comment by C-Bouthoorn** [comment] 2017-09-22 20:39
Closing in favour of the [master post](https://github.com/abe33/atom-pigments/issues/351).

**Closed by C-Bouthoorn** 2017-09-22 20:39 UTC
Labels: bug
