### ISSUE TITLE
Editor is not responding with pigments package installed

### ISSUE THREAD

**Issue by borzaka** [abe33/atom-pigments#421] opened 2019-03-14 11:10 UTC
If I open a CSS file which has hexa colors in it, after a couple of seconds, the Atom editor crashes. Keep Waiting doesn't help, it will popup again a minute later.
Sometimes after opening a single HTML/PHP causes the freezing as well.

![image](https://user-images.githubusercontent.com/1230402/54351082-f860d600-464e-11e9-8147-4e1e8717931a.png)

No settings was changed in the package options, everything left default in pigments.

I'am using these plugins:
```
atom-bootstrap3
atom-html-preview
autoprefixer
browser-plus
editorconfig
emmet
file-icons
file-watcher
highlight-selected
minimap
minimap-cursorline
minimap-highlight-selected
pigments
```

Versions:
```
Atom    : 1.35.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

`atom-pigments v0.40.2`

But it's started with an earlier version which forced me to reinstall Atom, and try my packages installing one-by-one to figure out which one is causing issues. And it turned out this one. Of course this was the last one I installed...

Edit - some additional info:
- alternative package: [highlight-colors](https://atom.io/packages/highlight-colors)
- installing a previous version (0.40.1) doesn't freeze - I'am using it without any problems
`apm install "pigments@0.40.1"`
(Tested on the latest Atom 1.35.1 x64 Windows 10)

**Comment by faaaaq** [comment] 2019-03-19 19:18
I am experiencing the same issue.  No error or popup or crash or anything, but MANY seconds of Atom freezing entirely any time code is edited.  Narrowed the issue down to Pigments, confirmed with a coworker they are having the same issue and when they disable Pigments it also resolves the issue for them.  I am not able to find a decent replacement for Pigments, so, hoping this gets resolved soon..  :(

**Comment by M00nD3v** [comment] 2019-04-22 10:10
I have downloaded pigments now and since it got installed, Atom always freezes after about 15 seconds. So enough time to disable it if I am fast. Hope this problem will be fixed soon.

**Comment by C-Bouthoorn** [comment] 2019-06-11 15:38
Yeah this is probably because of #351 - many many people experience this but the creator of this project (@abe33) has seemed to have abandoned it, and I myself don't have any time either to investigate. If anyone would be able to find the root of this, that would be amazing. Please discuss your findings in the master post (#351) as well to make research easier for whoever wants to help.

**Closed by C-Bouthoorn** 2019-06-11 15:38 UTC
