### ISSUE TITLE
Cannot find 'highlights-component' in the require cache.

### ISSUE THREAD

**Issue by jessicafndez** [abe33/atom-pigments#335] opened 2017-08-17 15:14 UTC
[Enter steps to reproduce:]

1. Just open Atom with new update

I tried to Uninstall/Install and Disable/Enable but didn't work :(

**Atom**: 1.19.2 ia32
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package 0.39.1

### Stack Trace

Failed to activate the pigments package

```
At Cannot find 'highlights-component' in the require cache.

Error: Cannot find 'highlights-component' in the require cache.
    at requireCore (/packages/pigments/lib/pigments.coffee:310:19)
    at Object.patchAtom (/packages/pigments/lib/pigments.coffee:312:26)
    at Object.activate (/packages/pigments/lib/pigments.coffee:16:6)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.19.2/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.19.2/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.19.2/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.19.2/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.19.2/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.19.2/resources/app/src/package-manager.js:645:40)
    at ~/AppData/Local/atom/app-1.19.2/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.19.2/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (~/AppData/Local/atom/app-1.19.2/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (~/AppData/Local/atom/app-1.19.2/resources/app/src/package-manager.js:603:52)
    at ~/AppData/Local/atom/app-1.19.2/resources/app/src/atom-environment.js:843:36
```

### Commands

```
```

### Non-Core Packages

```
atom-autocomplete-php 0.22.0 
atom-typescript 11.0.6 
autoclose-html 0.23.0 
busy-signal 1.4.3 
git-plus 7.3.3 
hyperclick 0.0.40 
intentions 1.1.2 
linter 2.2.0 
linter-ui-default 1.6.3 
nuclide 0.229.0 
php-integrator-annotations 1.1.1 
php-integrator-autocomplete-plus 1.2.0 
php-integrator-base 2.1.7 
php-integrator-call-tips 1.2.1 
php-integrator-core 2.0.2 
php-integrator-linter 1.3.0 
php-integrator-navigation 1.1.1 
php-integrator-symbol-viewer 0.6.4 
php-integrator-tooltips 1.1.3 
pigments 0.39.1 
platformio-ide-terminal 2.3.1 
project-manager 3.3.3 
Remote-FTP 0.10.7 
terminal-plus 0.14.5 
todo-show 1.11.0 
```

**Comment by C-Bouthoorn** [comment] 2017-08-17 21:04
Duplicate of https://github.com/abe33/atom-pigments/issues/334 https://github.com/abe33/atom-pigments/issues/329 https://github.com/abe33/atom-pigments/issues/328 https://github.com/abe33/atom-pigments/issues/318 and https://github.com/abe33/atom-pigments/issues/314.

Closing

**Closed by C-Bouthoorn** 2017-08-17 21:04 UTC

**Comment by theorise** [comment] 2017-08-18 08:12
All the duplicate tickets you linked to have been closed due to duplication and referenced this issue.

What issue should we be following?

**Comment by Wuyunong** [comment] 2017-08-29 11:13
because the highlights-component is not in NPM
find your .atom folder
npm install  pigments
