### ISSUE TITLE
Atom Helper hitting 100% CPU after opening project

### ISSUE THREAD

**Issue by felics** [abe33/atom-pigments#102] opened 2015-10-15 11:06 UTC
[Possibly related to #95 ]

Whenever I open or switch a project (managed with the `project-manager` package), the Atom Helper Process immediately jumps to 100% CPU Usage. I confirmed that `pigments` is the cause for this by disabling all other packages and re-enabling them one by one. The Atom Helper Process seems to have opened all `scss`-files in all of my repositories. `(Activity Monitor -> Process Info -> Open Files and Ports)` After closing Atom, the process keeps spinning @ 100% usage. The CPU usage is normal when opening Atom with an empty window.

**OS**: OSX 10.11
**Atom Version:** 1.0.19
**Atom Path**: /usr/local/bin/atom
**Atom Install Method:** brew-cask

**Comment by abe33** [comment] 2015-10-15 14:24
Thanks for the report.

> The Atom Helper Process seems to have opened all scss-files in all of my repositories

That's right, the default behavior is to scan all the scss/less/sass/styuls files in the project directories to build a list of all variables and colors in the project to properly evaluate the colors when it encouter one in a file. You can limit this by either setting the `sourceNames` setting to an empty string or to ignore this setting on a per-project basis using the `Pigments: Project Settings` command.

At one point, I had implemented a warning for huge project, but the UX was really suboptimal and I had to remove it. Instead I tried to improve the parsing performances. But still, if someone open a huge directory, the scanning of all the directories may take some time.

**Comment by felics** [comment] 2015-10-15 14:27
@abe33 Makes sense, thanks for the info. But why does the process keeps spinning after Atom is closed? Does it finish when it's done? If this is intended behaviour, feel free to close this issue.

**Comment by abe33** [comment] 2015-10-15 14:50
> But why does the process keeps spinning after Atom is closed? If this is intended behaviour, feel free to close this issue.

It's clearly not the intended behaviour! I may have forgot to kill the task on package deactivation, I'll check that because there's no point to keep scanning files after Atom was closed.
> Does it finish when it's done?

It should, actually I don't even rescan when a file is created or removed (maybe I should in this case).

**Comment by juanfernandoe** [comment] 2015-12-13 21:37
+1

**Comment by abe33** [comment] 2016-01-11 19:35
I reviewed the code and found a condition leading to an infinite loop when parsing an expression, I published a patch for this case, let me know if you find some improvements with the new version.

**Comment by felics** [comment] 2016-01-11 19:36
ty for your help, I'm going to test it tomorrow and get back to you

**Comment by felics** [comment] 2016-01-13 12:04
Seems to be fixed for me :beers:

**Comment by abe33** [comment] 2016-01-20 15:44
Glad to hear that, I'm closing this issue then. I'll still be looking for improvement in that area though.

**Closed by abe33** 2016-01-20 15:44 UTC
