### ISSUE TITLE
Editor lags with Pigments installed

### ISSUE THREAD

**Issue by trekitch** [abe33/atom-pigments#275] opened 2017-02-06 16:56 UTC
Whenever I have pigments installed my editor lags. By lag I mean i may be able to type a few things but then the editor will stop registering that I am typing anything like it is frozen. Then after I a few seconds it catches up to what I typed. This happens very often and really stops me from doing an coding. I know that it is pigments because when I uninstall it or disable it I no longer have the issue. 

I have also tried uninstalling and installing pigments multiple times. I am using Atom version 1.31.1

**Comment by nrleuenb** [comment] 2017-02-10 22:53
I also have this issue, though mine is a little more severe. Ever since the update to atom 1.13 I've seen my editor continually crash after using 110+% of my CPU. My suspicion is that this (the crash) has more to do with minimap-pigments than with pigments (and have added an issue accordingly: https://github.com/abe33/minimap-pigments/issues/8), but I do see some lag and high CPU usage with pigments, but not enough to be really disruptive. 

Do you have minimap-pigments installed, or are you just using the pigments package?

**Comment by trekitch** [comment] 2017-02-13 19:28
I am only using the pigments package.

**Comment by abe33** [comment] 2017-02-16 14:50
Hi there, it would be great if you could provide me with a timeline record and a profile record as well as some description of the kind of projects you're working on. Performances are highly dependent on the context (number of files, number of colors, etc...)

**Comment by raptor235** [comment] 2017-02-22 01:52
Just adding to this... I had my atom slow right down.. on certain files.. every time I type a keystroke I get a 1-2 second delay... it's unusable... it's been working fine for a while but I ran quite a few updates today and I think the latest update must have cause an issue.

**Comment by abe33** [comment] 2017-02-22 09:33
I'll really need more information. I mean, what's the version of the plugin you're using, what's your system, what's your Atom version, what's your config, what kind of project are you working on, etc.

**Comment by raptor235** [comment] 2017-02-22 13:13
I was having the problem on a PHP file, OSX, atom 1.14.3 your plugin version v0.39.0...

The file I was working was about a 1000 line file, php / html mix.

**Comment by xiomai** [comment] 2017-02-22 13:22
In my case even a newly  created file would freeze for like a second. v1.14.3, Windows 8.1.

**Comment by nrleuenb** [comment] 2017-02-22 22:33
@abe33 I am using v.0.39.0, OSX 12.3. It's an admittedly large project, but has very few colors. The project that I am currently working in has fewer than 10 colors in it, though there are also larger project files in the atom sidebar that have over a hundred colors in them, that I am not working on, nor  do I have any of their files open. I've updated to atom 1.14.3. The majority of my files are javascript.

There was a brief period of time when I wasn't seeing any issues, leading me to think it was caused by minimap-pigments, but the lag issue has come back, though atom is no longer crashing.

**Comment by nrleuenb** [comment] 2017-02-22 22:34
Does pigments parse the entire project or just the file that is open? Parsing only the file that is open would be a nice option for those of us who have huge project files, so we can use the package without atom crashing.

**Comment by abe33** [comment] 2017-02-23 09:39
@nrleuenb it scans the whole project for legit files, so that it can creates a list of available variable, which will then be used to compute the colors. ie, if you have a scss file with only a few variables that are then referenced in several other files, Pigments will be able to highlights these variables as it knows their values.
But this process is done on another thread, so it should have much impact on Atom's performances. If someone can use the profiling tool to get a record so that I can find what's causing the lag it'll be great!

**Comment by MouseEatsCat** [comment] 2017-03-06 15:06
I had set the Marker Type to native-dot and was seeing a lot of lag (and a large spike in cpu usage) when opening large file 6000+ lines. I tried switching it back to native-background and now everything is running fast.

It might be an issue with the Marker Type?

**Comment by jsieler** [comment] 2017-03-10 10:06
Same here. Working with JS files and whole editor freeze almost after every line change.

**Comment by JulianBerger** [comment] 2017-03-11 13:30
Same issue on windows and mac. Unusable with .js files...

**Comment by garrettw** [comment] 2017-04-28 16:35
Same issue here. I can't tell if it's the size of my CSS file (or the number of colors in it) making it lag... but I have noticed that high CPU usage is the culprit when it slows down, and disabling Pigments fixes it.
The reduction in performance is too big of a drawback for me to use this, so sadly I'll have to disable it until there's a fix for this.

**Comment by pixilz** [comment] 2017-05-08 01:37
I have been having this issue on:
Atom Version: 1.16.0
OS: Win 10 Pro x64
Project: Small about 20 scss files (Disabled pigment scans on my css)
Ram: 16GB
CPU: AMD FX-8320

With the project I am working I really needed something that provided the functionality of pigments and found that on Malwarebytes Premium Trial, v. 3.0.6.1469 if I disabled the "self-protection module" and left all other settings (including my Atom packages) untouched all of the lag disappeared. All of the lag would happen based on how long I set the "Delay Before Scan" option in Atom. (I.E. at 1000 it would lag after 1 second of no key presses). My assumption is that Malwarebytes (and potentially other services) are scanning or checking your scan before it lets it complete. 
Hopefully some of this was useful. 

Thanks for making and maintaining awesome package!

**Comment by C-Bouthoorn** [comment] 2017-05-08 15:16
It seems all of you (with an exception of @raptor235) use Windows, so presumably also a sort of Anti-Virus. That would explain why there are no people who experience this on Linux yet (because many Linux users don't use realtime AV).
@raptor235: Do you also run any sort of AV? That'd clear some things up.

I have no idea why AV matters in this case though...

**Comment by pixilz** [comment] 2017-05-08 15:19
It is worth noting I  have Avast, the settings I chose seemed to have no effect.

**Comment by ex-jedi** [comment] 2017-06-11 20:07
Same results here as @pixilz. Disabling Malwarebytes Premium self-protection removes any lag.

**Comment by caleb531** [comment] 2017-09-08 02:24
@C-Bouthoorn I have recently been experiencing this same lag issue on my macOS system. Disabling pigments (and pigments alone) immediately fixes the issue for me. Having pigments enabled always causes the following kinds of slowdowns:

- Laggy scrolling
- Serious lag when typing (~80 WPM), causing the editor to freeze up between keystrokes (i.e. can't scroll when frozen)
- When using `cmd-/` to toggle comments, a synchronous delay freezes up the editor; this delay is longer the more lines I have selected

macOS 10.12.6
Atom 1.19.7
About 561 non-gitignore'd files in entire project

```json
{
  "atom": "1.19.7",
  "pigments": "0.40.2",
  "platform": "darwin",
  "config": {
    "ignoredScopes": [
      "\\.comment",
      "\\.string",
      "\\.source\\.gfm"
    ],
    "markerType": "native-dot",
    "traverseIntoSymlinkDirectories": false,
    "sourceNames": [
      "**/*.css",
      "**/*.styl",
      "**/*.stylus",
      "**/*.less",
      "**/*.sass",
      "**/*.scss"
    ],
    "ignoredNames": [
      "vendor/*",
      "node_modules/*",
      "spec/*",
      "test/*"
    ],
    "ignoredBufferNames": [],
    "extendedSearchNames": [
      "**/*.css"
    ],
    "supportedFiletypes": [
      "*"
    ],
    "filetypesForColorWords": [
      "css",
      "less",
      "styl",
      "stylus",
      "sass",
      "scss"
    ],
    "autocompleteScopes": [
      ".source.css",
      ".source.css.less",
      ".source.sass",
      ".source.css.scss",
      ".source.stylus"
    ],
    "extendAutocompleteToVariables": false,
    "extendAutocompleteToColorValue": false,
    "autocompleteSuggestionsFromValue": false,
    "maxDecorationsInGutter": 100,
    "sassShadeAndTintImplementation": "compass",
    "sortPaletteColors": "none",
    "groupPaletteColors": "none",
    "mergeColorDuplicates": false,
    "delayBeforeScan": 500,
    "ignoreVcsIgnoredPaths": true,
    "notifyReloads": true,
    "dismissableReloadNotifications": true
  },
  "project": {
    "config": {},
    "paths": [
        "561 files listed here; redacted because this is a work-related project"
    ],
    "variables": {
      "colors": 882,
      "total": 3041
    }
  }
}
```

**Comment by Vlaoff** [comment] 2017-09-19 08:20
Have the same problem. Working on macOs.

With a fresh install of atom and only pigments installed, the editor makes the all system lag very hard when I open a project. It lags so hard that I need to wait a few minutes to just be able to move the mouse. If I wait long enough, eventually it will load the project and work almost without lags. But I need to wait 15 minutes, then click on continue working (on the atom popup) ant then wait again. 

The project I'm working on is quite big (laravel + customised bootstrap). But even on smaller projects it has the same issue (on wordpress themes)

**Comment by samc449** [comment] 2017-09-19 10:20
+1

**Comment by C-Bouthoorn** [comment] 2017-09-22 20:40
Closing in favour of the [master post](https://github.com/abe33/atom-pigments/issues/351).

**Closed by C-Bouthoorn** 2017-09-22 20:40 UTC
Labels: bug, more-information-needed
