### ISSUE TITLE
100% CPU With Pigments enabled.

### ISSUE THREAD

**Issue by Dayjo** [abe33/atom-pigments#169] opened 2016-03-30 11:49 UTC
Hello, 

Thanks for this great package! 

I don't know if this is just a local issue - it hasn't been an issue before today. But Atom is using ~100% CPU on my Mac today, and when I disable the Pigments package it drops, if I then re-enable it, it shoots back up again. 

Is there any particular information that I can retrieve that will be of some use?

Here's a screencast clearly showing it;

![](http://c.dayjo.me/322R0z033c0B/Screen%20Recording%202016-03-30%20at%2012.48%20pm.gif)

**Comment by houmark** [comment] 2016-03-31 07:32
Same for me. This has happened on and off with every release, but the last 3-5 releases has been better for me until the current version 0.26.0 which seems to be using all the CPU it can get.

**Comment by abe33** [comment] 2016-03-31 10:44
Hi there, this is likely a duplicate of #125, so I'll close this issue to keep the discussion in one place.

> Is there any particular information that I can retrieve that will be of some use?

Sure, please see my comments in #125 ([this one for instance](https://github.com/abe33/atom-pigments/issues/125#issuecomment-192751240)). The most critical thing being a sample project where the issue occurs so that I can reproduce it locally and analyze the problem (parsing being done off the main thread it's really hard to profile and get reported of the issues of the child worker)

**Closed by abe33** 2016-03-31 10:44 UTC
