### ISSUE TITLE
pigment plugin makes atom sluggy

### ISSUE THREAD

**Issue by hacker626** [abe33/atom-pigments#479] opened 2022-02-22 19:32 UTC
hello,dear
I was working with atom for my website development and suddenly the atom become sluggy and slow responding to my input.
I try with disabling various plugins and finally disabling "pigment" makes atom normal.
Please look into this issue

**Comment by Cxarli** [comment] 2022-04-10 12:08
Duplicate of #351

**Closed by Cxarli** 2022-04-10 12:08 UTC
