### ISSUE TITLE
Uncaught TypeError: Cannot read property 'NaN' of undefined

### ISSUE THREAD

**Issue by Pooh980219** [abe33/atom-pigments#385] opened 2018-03-06 03:18 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.12.6
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package 0.40.2

### Stack Trace

Uncaught TypeError: Cannot read property 'NaN' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:963

TypeError: Cannot read property 'NaN' of undefined
    at TextEditorComponent.renderedScreenLineForRow (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:963:37)
    at TextEditorComponent.screenPositionForPixelPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2399:33)
    at HTMLElement.screenPositionForPixelPosition (/app.asar/src/text-editor-element.js:250:32)
    at HTMLElement.ColorBufferElement.screenPositionForMouseEvent (/packages/pigments/lib/color-buffer-element.coffee:429:22)
    at HTMLElement.ColorBufferElement.colorMarkerForMouseEvent (/packages/pigments/lib/color-buffer-element.coffee:415:17)
    at Object.colorMarkerForMouseEvent (/packages/pigments/lib/pigments.coffee:221:25)
    at Object.shouldDisplayContextMenu (/packages/pigments/lib/pigments.coffee:215:5)
    at /packages/pigments/lib/pigments.coffee:111:36)
    at ContextMenuManager.module.exports.ContextMenuManager.cloneItemForEvent (/Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:167:25)
    at ContextMenuManager.module.exports.ContextMenuManager.templateForEvent (/Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:100:39)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:189:33)
    at WindowEventHandler.handleDocumentContextmenu (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:251:44)
```

### Commands

```
     -0:51.6.0 command-palette:toggle (input.hidden-input)
     -0:49.5.0 core:move-right (input.hidden-input)
     -0:48.6.0 core:move-down (input.hidden-input)
     -0:48.4.0 core:confirm (input.hidden-input)
     -0:48.4.0 sync-settings:backup (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
advanced-open-file 0.16.7 
atom-beautify 0.32.0 
atom-clock 0.1.16 
atom-ternjs 0.18.3 
autoclose-html 0.23.0 
autocomplete-modules 1.11.0 
autocomplete-paths 2.12.2 
browser-plus 0.0.98 
color-picker 2.2.5 
docblockr 0.13.7 
emmet 2.4.3 
file-icons 2.1.17 
highlight-selected 0.13.1 
language-babel 2.84.0 
language-markdown 0.25.1 
language-nginx 0.8.0 
language-postcss 1.3.1 
language-vue 0.23.1 
linter 2.2.0 
linter-csslint 2.0.0 
linter-eslint 8.4.1 
linter-scss-lint 3.1.1 
markdown-preview-plus 2.5.5 
markdown-writer 2.7.3 
merge-conflicts 1.4.5 
minimap 4.29.8 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
open-in-browsers 0.0.30 
pigments 0.40.2 
regex-railroad-diagram 0.19.4 
simplified-chinese-menu 5.3.5 
sync-settings 0.8.5 
vue2-autocomplete 0.1.0-alpha.4 
```

**Comment by nukeop** [comment] 2018-03-08 11:01
I just encountered this as well.

**Comment by C-Bouthoorn** [comment] 2018-03-08 16:03
Duplicate of #377

**Closed by C-Bouthoorn** 2018-03-08 16:03 UTC
