### ISSUE TITLE
It is not a color that I have established

### ISSUE THREAD

**Issue by unluisco** [abe33/atom-pigments#40] opened 2015-06-24 02:40 UTC
I have written the html ref for a dash, but the package as it takes me a color

![index html - users unluisco dropbox diseno y desarrollo personal 2 0 - atom 2015-06-23 21-33-31](https://cloud.githubusercontent.com/assets/6332263/8321753/75670776-19f0-11e5-9d65-83b92290a241.png)

**Comment by abe33** [comment] 2015-06-26 20:27
Yes, it's a duplicate of #39, i still need to figure how to workaround that.

**Closed by abe33** 2015-06-26 20:27 UTC
