### ISSUE TITLE
Cannot find 'highlights-component' in the require cache.

### ISSUE THREAD

**Issue by amarin1990** [abe33/atom-pigments#341] opened 2017-08-27 20:01 UTC

**Comment by C-Bouthoorn** [comment] 2017-08-28 10:44
Duplicate of https://github.com/abe33/atom-pigments/issues/335 https://github.com/abe33/atom-pigments/issues/334 https://github.com/abe33/atom-pigments/issues/329 https://github.com/abe33/atom-pigments/issues/328 https://github.com/abe33/atom-pigments/issues/318 https://github.com/abe33/atom-pigments/issues/314 https://github.com/abe33/atom-pigments/issues/201 https://github.com/abe33/atom-pigments/issues/338

**Closed by C-Bouthoorn** 2017-08-28 10:44 UTC
