### ISSUE TITLE
Pigments Color issue

### ISSUE THREAD

**Issue by shoaibdhk** [abe33/atom-pigments#384] opened 2018-02-20 02:58 UTC
I am having problem when I change my marker type from Default (native-background). After change, it shows only 50 lines color code and after that it doesn't show at all. I have tried my other PC but it didn't work. Any solution at that. I have reinstalled numerous times but didn't help.

**Comment by overtopcode** [comment] 2018-02-26 16:55
I am having problem when i select color hex and click with right button's mouse.
Atom gives me error:
Uncaught TypeError: Cannot read property 'NaN' of undefined
What can i do?
Thank you very much for your answers and support

**Comment by C-Bouthoorn** [comment] 2018-03-08 16:05
@shoaibdhk Duplicate of #342 or #369 

@overtopcode Duplicate of #377

**Closed by C-Bouthoorn** 2018-03-08 16:05 UTC
