### ISSUE TITLE
Uncaught TypeError: Cannot read property 'NaN' of undefined

### ISSUE THREAD

**Issue by broham89** [abe33/atom-pigments#399] opened 2018-06-06 13:26 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.4
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package 0.40.2

### Stack Trace

Uncaught TypeError: Cannot read property 'NaN' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:977

TypeError: Cannot read property 'NaN' of undefined
    at TextEditorComponent.renderedScreenLineForRow (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:977:37)
    at TextEditorComponent.pixelLeftForRowAndColumn (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2379:35)
    at TextEditorComponent.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:204:46)
    at HTMLElement.pixelPositionForScreenPosition (/app.asar/src/text-editor-element.js:246:32)
    at /packages/pigments/lib/color-buffer-element.coffee:327:36)
    at HTMLElement.ColorBufferElement.updateDotDecorationsOffsets (/packages/pigments/lib/color-buffer-element.coffee:319:7)
    at /packages/pigments/lib/color-buffer-element.coffee:250:14
    at Array.forEach (native)
    at /packages/pigments/lib/color-buffer-element.coffee:249:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at disposables.add.displayLayer.onDidChange.changes (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:614:26)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayLayer.emitDeferredChangeEvents (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:819:26)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1800:30)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:996:18)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2002:30)
    at TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2875:23)
    at TextEditor.setCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2686:23)
    at TextEditorComponent.didMouseDownOnContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1808:25)
```

### Commands

```
     -3:28.2.0 open-in-browser:open (span.syntax--comment.syntax--block.syntax--html)
     -0:57.2.0 autocomplete-plus:confirm (input.hidden-input)
     -0:38.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-live-server 2.2.0 
busy-signal 1.4.3 
chester-atom-syntax 0.3.0 
emmet 2.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-scss-lint 3.1.1 
linter-ui-default 1.7.1 
minimap 4.29.7 
open-in-browser 0.5.2 
pigments 0.40.2 
```

**Comment by C-Bouthoorn** [comment] 2018-06-06 18:50
Duplicate of https://github.com/abe33/atom-pigments/issues/354

**Closed by C-Bouthoorn** 2018-06-06 18:50 UTC
